// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresAPI.Data;

#nullable disable

namespace MyWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818063113_AddRefreshTokenToUsers")]
    partial class AddRefreshTokenToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("refreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PostgresAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("aracId")
                        .HasColumnType("integer")
                        .HasColumnName("aracid");

                    b.Property<DateOnly>("veriTarihi")
                        .HasColumnType("date")
                        .HasColumnName("veritarihi");

                    b.Property<string>("aracPlaka")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aracplaka");

                    b.Property<float>("hiz")
                        .HasColumnType("real")
                        .HasColumnName("hiz");

                    b.Property<float>("kmSayaci")
                        .HasColumnType("real")
                        .HasColumnName("kmsayaci");

                    b.HasKey("aracId", "veriTarihi");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
